class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'unzipmirror3'
        self.TarMirrorCommand = 'tarmirror3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list'
        self.StatusCommand = 'status3'
        self.AuthorizedUsersCommand = 'user'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stat'
        self.HelpCommand = 'help3'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone3'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.DeleteCommand = 'delete3'
        self.UsageCommand = 'usage'
        self.MediaInfoCommand = 'mediainfo'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update3'

BotCommands = _BotCommands()
